version: 2.1

executors:
  docker-build-executor:
    environment:
      IMAGE_NAME: formatool/gitpod-workspace-cassandra:latest
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-and-push:
    environment: 
      DOCKERFILE: Dockerfile
    executor: docker-build-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |            
            docker build -t $IMAGE_NAME -f $DOCKERFILE .
      - run:
          name: Publish Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME
            
workflows:
  version: 2
  build-master:
    jobs:
      - build-and-push